name: Nocobase Build Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
      - 'develop'
    paths:
      - '.github/workflows/nocobase-build-test.yml'
      - 'packages/**'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/nocobase-build-test.yml'
      - 'packages/**'

jobs:
  build-test:
    strategy:
      matrix:
        node_version: [ '18' ]
    runs-on: ubuntu-latest
    container: node:${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
    timeout-minutes: 30
